skipgram_version: softmax

dataset: normalized_shakespeare.txt
data_dir: data/
train_batch_size: 96

optimizer: Adam
learning_rate: 0.025
epochs: 5

checkpoint_frequency: 
model_dir: weights/cbow_WikiText2
